spring:
  datasource:
    url: jdbc:postgresql://address-db-prod:5432/addressservice
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


server:
  port: 8090
  error:
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true
