spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authserverDB
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true

jwt:
  expiration: 600000
  secret: r9qSZrihqYt79JPbHpAaD//OX8RICTOIRGPzESiHbiGT1Ppc4G1uMTbLu5Lw7/o6GSbtpEPZmzMELKH1G1qirjerCbpASu3DZYN1AsGgMZ9JEhSwzwYzfp0h8Ooqu2R1r/s2qiN+PxInHX1uee8yQcwBEIkaU9U3EUMvSYsdY+CBSWsIJeywC9p9hWJn1cBcFBBHjDQ0zJrEK6bwDfRI9DGatN+thR8OmEzER/RKyYv8AFQxeYsw3ZZC+nry2kgm5T48NlEyqhif0logyzAYvRAIpjhV+n/yXJe0D6CJOyMiPaYT217JHdStcD3THjVtGgIoF0mSWkOMFvLGdTLb4WYcx3jORFC+MshYzhDGFkY=
