#spring:
 # datasource:
  #  url: jdbc:postgresql://localhost:5432/cartservice
   # username: postgres
    #password: test
  #jpa:
   # properties:
    #  hibernate:
     #   dialect: org.hibernate.dialect.PostgreSQLDialect
    #hibernate:
     # ddl-auto: update

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cartservice

      
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true
