spring:
  data:
    mongodb:
      uri: mongodb://cart-db:27017/cartservice

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

      
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://cart-db-prod:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true
