spring:
  datasource:
    url: jdbc:postgresql://product-db-prod:5432/productservice
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true
